os:
  - linux
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.0"
  - "node"
  - "iojs-v1.1.0"
  - "iojs-v2.0.0"
  - "iojs-v3.0.0"
  - "iojs-v3.1.0"
  - "iojs-v3.2.0"
  - "iojs-v3.3.0"
  - "iojs"
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
  - make travis
